export const SIGN_IN = 'SIGN_IN';
export const SIGN_OFF = 'SIGN_OFF';
export const SET_CURRENT_QUESTION = 'SET_CURRENT_QUESTION';
export const SET_QUESTION_QUEUE = 'SET_QUESTION_QUEUE';
export const SET_QUESTION_OBJECT = 'SET_QUESTION_OBJECT';
export const SET_USERNAME = 'SET_USERNAME';